apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - env:
          - name: MYSQL_DATABASE
            value: demo
          - name: MYSQL_PASSWORD
            value: Password123!
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"
        - name: mariadb
          image: mariadb/server:10.4
          #command: ["mariadb", "--host", "127.0.0.1", "-P", "3306", "--user", "root", "-p", "Password123!"]
          ports:
            - containerPort: 3306
          #env:
            #- name: MARIADB_ROOT_PASSWORD
              #value: "Password123!"
            #- name: MARIADB_DATABASE
             # value: demo