apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Password123!"
            - name: MYSQL_DATABASE
              value: "demo"
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
          image: mysql:5.7
          ports:
            - containerPort: 3306
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
      restartPolicy: Always
