apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: db-port
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-volume
          volumes:
          - name: mysql-volume
            persistentVolumeClaim:
              claimName: db-data
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "Password123!"
            - name: MARIADB_DATABASE
              value: "demo"
