apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  labels:
    app: rest
spec:
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      imagePullSecrets:
        - name: gitlab-registry-credentials
      containers:
        - name: rest
          image: {{ CI_REGISTRY_IMAGE }}/rest:latest
          resources:
            limits:
              cpu: 50m
              memory: 100M
          ports:
            - containerPort: 5000