---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqllite
  name: sqllite
spec:
  selector:
    matchLabels:
      app: sqllite
  template:
    metadata:
      labels:
        app: sqllite
    spec:
      containers:
        -
          image: "git.mylab.th-luebeck.de:4181/webtech/ss2022/julian-hardekopf/backendsql"
          name: sqllite
          ports:
            -
              containerPort: 6379
          resources:
            limits:
              cpu: 50m
              memory: 100M
          volumeMounts:
            -
              mountPath: /data
              name: sqllite-volume
      imagePullSecrets:
        -
          name: gitlab-registry-credentials
      volumes:
        -
          name: sqllite-volume
          persistentVolumeClaim:
            claimName: sqllite-pvc
