apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-deployment
  labels:
    app: prime
spec:
  replicas: 5
  selector:
    matchLabels:
      app: prime
  template:
    metadata:
      labels:
        app: prime
    spec:
      imagePullSecrets:
        - name: gitlab-registry-credentials
      containers:
        - name: prime
          image: "{{ CI_REGISTRY_IMAGE }}/sqllite:latest"
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: "redis-service"
          resources:
            limits:
              cpu: "50m"
              memory: "128Mi"

